#!/usr/bin/env python3
"""Apply overlay/annotations.json to the spec, writing spec/openapi.annotated.json.

    tools/annotate-spec.py                       # write the annotated spec
    tools/annotate-spec.py --docs docs/ANNOTATIONS.md
    tools/annotate-spec.py --check               # verify the committed files are current (for CI)
    tools/annotate-spec.py --summary             # what the overlay adds, counted

The published description has a `description` on exactly one of its 240 operations, documents no
error but 422, declares OAuth2 with no flows, and omits routes the service answers. Everything a
caller needs to know therefore has nowhere to live in it — so it is written in, here.

The application itself is `tools/annotate.jq`, which is the single implementation: synchra-php
vendors the same file and runs it during its own fetch. This script is the wrapper that adds the
things a CI job wants — staleness checks, a rendered copy, a summary — and nothing about *what* an
annotation means lives here.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def text(value: str | list[str]) -> str:
    """Overlay prose is written as a list of lines, so it stays reviewable in a diff."""
    return value if isinstance(value, str) else "\n".join(value)


def apply(spec: Path, overlay: Path, program: Path) -> str:
    """Run the jq overlay. Its own error messages are the useful ones, so they pass straight through."""
    done = subprocess.run(
        ["jq", "--argjson", "overlay", overlay.read_text(encoding="utf-8"), "--from-file", str(program)],
        stdin=spec.open("rb"),
        capture_output=True,
        text=True,
        check=False,
    )

    if done.returncode != 0:
        raise SystemExit(done.stderr.strip() or f"jq failed with status {done.returncode}")

    return done.stdout


def render_docs(overlay: dict) -> str:
    """Render the overlay as Markdown, so it is readable without opening a 1.3 MB JSON file.

    Generated, not written by hand: the overlay is the one copy of this text. Anything maintained
    alongside it would drift, and a note that contradicts the one in the docblock is worse than no
    note at all.
    """
    out = [
        "<!-- Generated by tools/annotate-spec.py from overlay/annotations.json. Do not edit. -->",
        "",
        "# Annotations",
        "",
        "What the API description would say about each endpoint and field if we could write it.",
        "These are applied to `spec/openapi.annotated.json`, so a generated client carries them in",
        "its docblocks; this page is the same text, readable.",
        "",
        "Cross-cutting facts — how the document is published, how it drifts, how the gift tables",
        "behave — are in [CAVEATS.md](CAVEATS.md) instead, because they have no endpoint to hang on.",
        "",
    ]

    if overlay.get("info"):
        out += ["## Across the whole API", "", text(overlay["info"]), ""]

    add = overlay.get("add") or {}

    if add.get("paths"):
        out += [
            "## Routes the description omits",
            "",
            "The service answers these; the published document does not list them.",
            "",
        ]

        for path, node in add["paths"].items():
            for method, operation in node.items():
                out += [f"### `{method.upper()} {path}`", "", operation.get("description", ""), ""]

    if add.get("schemas"):
        out += [
            "## Schemas the description omits",
            "",
            "Gateway payloads named by `spec/websocket.md` but defined in no schema.",
            "",
        ]

        for name, node in add["schemas"].items():
            fields = ", ".join(f"`{f}`" for f in (node.get("properties") or {}))
            out += [f"### `{name}`", "", node.get("description", ""), "", f"Fields: {fields}", ""]

    if overlay.get("errors"):
        rules = {
            "always": "every operation",
            "authenticated": "every operation that is not in `public`",
            "identified": "every operation whose path takes a parameter",
        }
        out += [
            "## Error responses",
            "",
            "The published description documents no error but 422. These are added by rule, and every",
            "body is the `Error` schema.",
            "",
            "| Status | Added to | Meaning |",
            "| :--- | :--- | :--- |",
        ]

        for rule, where in rules.items():
            for status, response in (overlay["errors"].get(rule) or {}).items():
                summary = response.get("description", "").split(".")[0]
                out += [f"| `{status}` | {where} | {summary} |"]

        out += [""]

    if overlay.get("public"):
        out += [
            "## Verified public",
            "",
            "Each of these answers without a token — checked with an unauthenticated request, not",
            "inferred from the document. They are marked `security: []` in the annotated spec.",
            "",
        ]
        out += [f"- `{entry}`" for entry in overlay["public"]]
        out += [""]

    if overlay.get("operations"):
        out += ["## Operations", ""]

        for target, note in overlay["operations"].items():
            out += [f"### `{target}`", "", text(note), ""]

    if overlay.get("schemas"):
        out += ["## Schemas and fields", ""]

        for target, note in overlay["schemas"].items():
            out += [f"### `{target}`", "", text(note), ""]

    return "\n".join(out).rstrip() + "\n"


def summarise(before: dict, after: dict, overlay: dict) -> list[str]:
    def responses(spec: dict) -> int:
        return sum(
            len(operation.get("responses") or {})
            for node in spec["paths"].values()
            for method, operation in node.items()
            if method in {"get", "post", "put", "delete", "patch"}
        )

    def described(spec: dict) -> int:
        return sum(
            1
            for node in spec["paths"].values()
            for method, operation in node.items()
            if method in {"get", "post", "put", "delete", "patch"} and operation.get("description")
        )

    def schemes(spec: dict) -> int:
        return len(spec["components"].get("securitySchemes") or {})

    rows = [
        ("paths", len(before["paths"]), len(after["paths"])),
        ("schemas", len(before["components"]["schemas"]), len(after["components"]["schemas"])),
        ("documented responses", responses(before), responses(after)),
        ("operations with a description", described(before), described(after)),
        ("security schemes", schemes(before), schemes(after)),
        ("marked public", 0, len(overlay.get("public") or [])),
    ]

    return [f"{label:<30} {was:5d} -> {now:5d}" for label, was, now in rows]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", type=Path, default=ROOT / "spec/openapi.json")
    parser.add_argument("--overlay", type=Path, default=ROOT / "overlay/annotations.json")
    parser.add_argument("--program", type=Path, default=ROOT / "tools/annotate.jq")
    parser.add_argument("--output", type=Path, default=ROOT / "spec/openapi.annotated.json")
    parser.add_argument("--docs", type=Path, help="also render the notes as Markdown")
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the output (and --docs, if given) is not what this would write",
    )
    parser.add_argument("--summary", action="store_true", help="print what the overlay changed")
    args = parser.parse_args()

    rendered = apply(args.spec, args.overlay, args.program)
    overlay = json.loads(args.overlay.read_text(encoding="utf-8"))
    docs = render_docs(overlay) if args.docs else None

    if args.check:
        stale = []

        if not args.output.exists() or args.output.read_text(encoding="utf-8") != rendered:
            stale.append(str(args.output))

        if docs is not None and (
            not args.docs.exists() or args.docs.read_text(encoding="utf-8") != docs
        ):
            stale.append(str(args.docs))

        if stale:
            print(
                "stale, run tools/annotate-spec.py and commit the result:\n  "
                + "\n  ".join(stale),
                file=sys.stderr,
            )

            return 1

        print("annotated spec and rendered notes are current")

        return 0

    args.output.write_text(rendered, encoding="utf-8")
    print(f"wrote {args.output}")

    if docs is not None:
        args.docs.write_text(docs, encoding="utf-8")
        print(f"wrote {args.docs}")

    if args.summary:
        before = json.loads(args.spec.read_text(encoding="utf-8"))
        print()

        for line in summarise(before, json.loads(rendered), overlay):
            print(f"  {line}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
